<!doctype html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <title>Mini Projet Authentification</title>

    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <link rel="stylesheet" href="assets/styles/css/style.css">
    <script src="https://kit.fontawesome.com/dbf8b52bf4.js" crossorigin="anonymous"></script>
</head>

<body>
    <?php
    require _header.phtml;
    require "$template".".phtml";
    require _footer.phtml;
    ?>    
</body>
</html>